<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Click to see screenshot...]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Thu_Jun_25_12_16_45_IST_2020.png>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Thu_Jun_25_12_16_45_IST_2020.png><img src=Thu_Jun_25_12_16_45_IST_2020.png height=200 width=200></img></a>]]>
    </line>
    <line>
      <![CDATA[Click to see screenshot...]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Thu_Jun_25_12_17_15_IST_2020.png>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Thu_Jun_25_12_17_15_IST_2020.png><img src=Thu_Jun_25_12_17_15_IST_2020.png height=200 width=200></img></a>]]>
    </line>
  </reporter-output>
  <suite name="Page Object Model" duration-ms="60762" started-at="2020-06-25T12:16:15 IST" finished-at="2020-06-25T12:17:15 IST">
    <groups>
    </groups>
    <test name="Login Test" duration-ms="30618" started-at="2020-06-25T12:16:15 IST" finished-at="2020-06-25T12:16:45 IST">
      <class name="com.kmv.testcases.LoginTest">
        <test-method status="FAIL" signature="loginTest(java.util.Hashtable)[pri:0, instance:com.kmv.testcases.LoginTest@38be305c]" name="loginTest" duration-ms="29122" started-at="2020-06-25T12:16:15 IST" data-provider="dp" finished-at="2020-06-25T12:16:44 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=zohokmv2020, runmode=y, username=venkateshkm2001@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login test failed..]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login test failed..
at org.testng.Assert.fail(Assert.java:97)
at com.kmv.testcases.LoginTest.loginTest(LoginTest.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click to see screenshot...]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Thu_Jun_25_12_16_45_IST_2020.png>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Thu_Jun_25_12_16_45_IST_2020.png><img src=Thu_Jun_25_12_16_45_IST_2020.png height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginTest -->
      </class> <!-- com.kmv.testcases.LoginTest -->
    </test> <!-- Login Test -->
    <test name="Create Account Test" duration-ms="30098" started-at="2020-06-25T12:16:45 IST" finished-at="2020-06-25T12:17:15 IST">
      <class name="com.kmv.testcases.LoginTest">
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.kmv.testcases.LoginTest@38be305c]" name="tearDown" is-config="true" duration-ms="1784" started-at="2020-06-25T12:17:16 IST" finished-at="2020-06-25T12:17:17 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.kmv.testcases.LoginTest -->
      <class name="com.kmv.testcases.CreateAccountTest">
        <test-method status="FAIL" signature="createAccountTest(java.util.Hashtable)[pri:0, instance:com.kmv.testcases.CreateAccountTest@56f6d40b]" name="createAccountTest" duration-ms="29380" started-at="2020-06-25T12:16:45 IST" data-provider="dp" finished-at="2020-06-25T12:17:15 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{accountname=Venkata}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Create account test failed...]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Create account test failed...
at org.testng.Assert.fail(Assert.java:97)
at com.kmv.testcases.CreateAccountTest.createAccountTest(CreateAccountTest.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click to see screenshot...]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Thu_Jun_25_12_17_15_IST_2020.png>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Thu_Jun_25_12_17_15_IST_2020.png><img src=Thu_Jun_25_12_17_15_IST_2020.png height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- createAccountTest -->
      </class> <!-- com.kmv.testcases.CreateAccountTest -->
    </test> <!-- Create Account Test -->
  </suite> <!-- Page Object Model -->
</testng-results>
